"use client";

import Link from "next/link";
import { AlertCircle, ArrowRight, Bot, Boxes, CheckCircle2, CircleDollarSign, Clock3, PackageCheck, PackageX, RefreshCw, ShieldCheck, ShoppingCart, Sparkles, UsersRound, Zap } from "lucide-react";
import { useCustomers } from "@/hooks/useCustomers";
import { useOrders } from "@/hooks/useOrders";
import { useProducts } from "@/hooks/useProducts";

const rupiah = new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 });
const successful = new Set(["paid", "shipped", "completed"]);

export default function CommandCenterPage() {
  const { orders, isLoading: ordersLoading, error, refresh } = useOrders();
  const { products, isLoading: productsLoading } = useProducts();
  const { customers, isLoading: customersLoading } = useCustomers();
  const loading = ordersLoading || productsLoading || customersLoading;
  const productById = new Map(products.map((product) => [product.id, product]));
  const paidOrders = orders.filter((order) => successful.has(order.status));
  const revenue = paidOrders.reduce((sum, order) => sum + order.total_amount, 0);
  const pending = orders.filter((order) => order.status === "pending");
  const pendingValue = pending.reduce((sum, order) => sum + order.total_amount, 0);
  const lowStock = products.filter((product) => product.stock > 0 && product.stock <= product.reorder_point);
  const stockOut = products.filter((product) => product.stock === 0);
  const conversion = orders.length ? Math.round((paidOrders.length / orders.length) * 100) : 0;
  const recent = orders.slice(0, 5);
  const priorities = [
    ...(pending.length ? [{ href: "/orders", icon: <Clock3 className="h-5 w-5" />, tone: "amber", title: `${pending.length} pembayaran masih menunggu`, detail: `${rupiah.format(pendingValue)} belum terkonfirmasi dalam order pending.` }] : []),
    ...(lowStock.length ? [{ href: "/products", icon: <Boxes className="h-5 w-5" />, tone: "amber", title: `${lowStock.length} produk stok menipis`, detail: lowStock.slice(0, 2).map((p) => p.name).join(", ") + (lowStock.length > 2 ? ", dan lainnya." : ".") }] : []),
    ...(stockOut.length ? [{ href: "/products", icon: <PackageX className="h-5 w-5" />, tone: "rose", title: `${stockOut.length} produk stok habis`, detail: "Produk ini tidak boleh dipromosikan atau dinegosiasikan sampai stok diperbarui." }] : []),
  ];

  return <div className="space-y-7 pb-10"><header className="relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-indigo-950 via-[#44358f] to-[#715bc9] px-7 py-8 text-white shadow-2xl shadow-indigo-200 md:px-9"><div className="absolute -right-16 -top-20 h-64 w-64 rounded-full bg-white/10 blur-2xl" /><div className="relative flex flex-wrap items-start justify-between gap-5"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-indigo-200"><Sparkles className="h-4 w-4" /> Command Center</p><h1 className="mt-3 text-3xl font-black tracking-tight md:text-4xl">Kendalikan penjualan dari satu layar.</h1><p className="mt-3 max-w-2xl text-sm leading-relaxed text-indigo-100">Dari percakapan WhatsApp hingga settlement Midtrans: lihat sinyal yang perlu ditindaklanjuti, tanpa kehilangan kendali atas margin dan stok.</p></div><button onClick={() => void refresh()} className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-bold text-indigo-950 shadow-lg transition hover:bg-indigo-50"><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} /> Segarkan</button></div><div className="relative mt-7 grid gap-3 text-xs font-semibold sm:grid-cols-3"><Pill icon={<ShieldCheck className="h-3.5 w-3.5" />} text="Floor price selalu terlindungi" /><Pill icon={<PackageCheck className="h-3.5 w-3.5" />} text="Stok dipantau per ambang restock" /><Pill icon={<Zap className="h-3.5 w-3.5" />} text="Checkout & payment teraudit" /></div></header>
  {error && <div className="flex gap-3 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800"><AlertCircle className="h-5 w-5 shrink-0" />{error}</div>}
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<CircleDollarSign />} label="Pendapatan terealisasi" value={rupiah.format(revenue)} note={`${paidOrders.length} order berstatus paid/fulfillment`} /><Metric icon={<Clock3 />} label="Menunggu pembayaran" value={rupiah.format(pendingValue)} note={`${pending.length} order perlu ditindaklanjuti`} tone="amber" /><Metric icon={<UsersRound />} label="Pelanggan WhatsApp" value={String(customers.length)} note="Identitas pelanggan unik tersimpan" tone="violet" /><Metric icon={<ShoppingCart />} label="Konversi order" value={`${conversion}%`} note="Paid, dikirim, atau selesai dari seluruh order" tone="emerald" /></section>
  <section className="grid gap-6 xl:grid-cols-[1.25fr_0.75fr]"><div className="rounded-3xl border border-white bg-white/85 p-6 shadow-xl shadow-indigo-100/40"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#715bc9]">Prioritas hari ini</p><h2 className="mt-1 text-xl font-black text-indigo-950">Apa yang perlu dilakukan sekarang</h2></div><span className="rounded-xl bg-indigo-50 px-3 py-2 text-xs font-bold text-[#715bc9]">{priorities.length} tindakan</span></div><div className="mt-6 space-y-3">{loading ? <Skeletons count={3} /> : priorities.length ? priorities.map((item) => <Link key={item.title} href={item.href} className="group flex gap-4 rounded-2xl border border-slate-100 bg-slate-50/70 p-4 transition hover:border-indigo-200 hover:bg-white hover:shadow-md"><div className={`h-fit rounded-xl p-2.5 ${item.tone === "rose" ? "bg-rose-100 text-rose-600" : "bg-amber-100 text-amber-600"}`}>{item.icon}</div><div className="min-w-0 flex-1"><p className="font-bold text-indigo-950">{item.title}</p><p className="mt-1 text-sm leading-relaxed text-slate-500">{item.detail}</p></div><ArrowRight className="mt-2 h-4 w-4 shrink-0 text-slate-300 transition group-hover:translate-x-1 group-hover:text-[#715bc9]" /></Link>) : <div className="rounded-2xl bg-emerald-50 p-6 text-center"><CheckCircle2 className="mx-auto h-8 w-8 text-emerald-500" /><p className="mt-3 font-bold text-emerald-900">Operasional terkendali</p><p className="mt-1 text-sm text-emerald-700">Tidak ada stok kritis atau pembayaran pending saat ini.</p></div>}</div></div>
  <div className="rounded-3xl border border-white bg-white/85 p-6 shadow-xl shadow-indigo-100/40"><p className="text-xs font-bold uppercase tracking-wider text-[#715bc9]">Kesiapan katalog</p><h2 className="mt-1 text-xl font-black text-indigo-950">Produk siap dijual</h2><div className="mt-6 space-y-4"><Progress label="Produk aktif" value={products.filter((p) => p.is_active).length} total={products.length} color="bg-[#715bc9]" /><Progress label="Stok aman" value={products.filter((p) => p.stock > 5).length} total={products.length} color="bg-emerald-500" /><Progress label="Butuh perhatian" value={lowStock.length + stockOut.length} total={products.length} color="bg-amber-500" /></div><Link href="/products" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#715bc9]">Kelola katalog <ArrowRight className="h-4 w-4" /></Link></div></section>
  <section className="grid gap-6 xl:grid-cols-[1.25fr_0.75fr]"><div className="rounded-3xl border border-white bg-white/85 p-6 shadow-xl shadow-indigo-100/40"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#715bc9]">Aktivitas transaksi</p><h2 className="mt-1 text-xl font-black text-indigo-950">Order terbaru</h2></div><Link href="/orders" className="text-sm font-bold text-[#715bc9]">Lihat semua</Link></div><div className="mt-6 overflow-hidden rounded-2xl border border-slate-100"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-[10px] font-bold uppercase tracking-wider text-slate-400"><tr><th className="p-4">Produk</th><th className="p-4">Jumlah</th><th className="p-4">Total</th><th className="p-4">Status</th></tr></thead><tbody>{loading ? <tr><td colSpan={4} className="p-4"><Skeletons count={2} /></td></tr> : recent.length ? recent.map((order) => <tr key={order.id} className="border-t border-slate-100"><td className="p-4 font-bold text-indigo-950">{productById.get(order.product_id)?.name || "Produk arsip"}<p className="mt-1 font-mono text-[10px] text-slate-400">#{order.id.slice(0, 8)}</p></td><td className="p-4 text-slate-600">{order.quantity} unit</td><td className="p-4 font-bold text-indigo-950">{rupiah.format(order.total_amount)}</td><td className="p-4"><StatusBadge status={order.status} /></td></tr>) : <tr><td colSpan={4} className="p-8 text-center text-slate-500">Belum ada order tersimpan.</td></tr>}</tbody></table></div></div>
  <div className="rounded-3xl border border-white bg-gradient-to-br from-white to-indigo-50 p-6 shadow-xl shadow-indigo-100/40"><div className="rounded-2xl bg-[#715bc9] p-3 text-white shadow-lg shadow-indigo-200"><Bot className="h-6 w-6" /></div><p className="mt-5 text-xs font-bold uppercase tracking-wider text-[#715bc9]">Mode presentasi</p><h2 className="mt-1 text-xl font-black text-indigo-950">Tunjukkan AI yang bisa dipertanggungjawabkan.</h2><p className="mt-3 text-sm leading-relaxed text-slate-600">Demo Sales Brain memperlihatkan keputusan harga deterministik, guardrail, dan respons natural—bukan sekadar chat biasa.</p><Link href="/sales-brain" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[#715bc9] px-4 py-3 text-sm font-bold text-white shadow-md transition hover:bg-[#5f49b5]">Buka Live Demo <ArrowRight className="h-4 w-4" /></Link></div></section></div>;
}
function Pill({ icon, text }: { icon: React.ReactNode; text: string }) { return <span className="inline-flex items-center gap-1.5 rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-indigo-50">{icon}{text}</span>; }
function Metric({ icon, label, value, note, tone = "indigo" }: { icon: React.ReactNode; label: string; value: string; note: string; tone?: "indigo" | "amber" | "violet" | "emerald" }) { const color = { indigo: "bg-indigo-50 text-[#715bc9]", amber: "bg-amber-50 text-amber-600", violet: "bg-violet-50 text-violet-600", emerald: "bg-emerald-50 text-emerald-600" }; return <div className="rounded-3xl border border-white bg-white/85 p-5 shadow-lg shadow-indigo-100/30"><div className={`inline-flex rounded-2xl p-3 ${color[tone]}`}>{icon}</div><p className="mt-4 text-xs font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-2xl font-black text-indigo-950">{value}</p><p className="mt-2 text-xs text-slate-500">{note}</p></div>; }
function Progress({ label, value, total, color }: { label: string; value: number; total: number; color: string }) { const width = total ? Math.round((value / total) * 100) : 0; return <div><div className="flex justify-between text-sm"><span className="font-semibold text-slate-600">{label}</span><span className="font-black text-indigo-950">{value}/{total}</span></div><div className="mt-2 h-2.5 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${color}`} style={{ width: `${width}%` }} /></div></div>; }
function StatusBadge({ status }: { status: string }) { const color: Record<string, string> = { pending: "bg-amber-100 text-amber-700", paid: "bg-sky-100 text-sky-700", shipped: "bg-violet-100 text-violet-700", completed: "bg-emerald-100 text-emerald-700", cancelled: "bg-rose-100 text-rose-700" }; return <span className={`rounded-full px-2.5 py-1 text-xs font-bold capitalize ${color[status] || "bg-slate-100 text-slate-600"}`}>{status}</span>; }
function Skeletons({ count }: { count: number }) { return <div className="space-y-3">{Array.from({ length: count }).map((_, index) => <div key={index} className="h-14 animate-pulse rounded-xl bg-slate-100" />)}</div>; }
