import { AudioLines, Bot, CheckCircle2, CreditCard, Database, MessageCircle, ShieldCheck, Sparkles } from "lucide-react";

const stages = [
  { number: "01", icon: MessageCircle, title: "Pelanggan masuk lewat WhatsApp", detail: "Meta Cloud API menerima teks atau voice note. Nomor WhatsApp dan wamid menjadi jejak identitas percakapan.", tone: "bg-indigo-50 text-indigo-700" },
  { number: "02", icon: AudioLines, title: "Voice note menjadi teks", detail: "Audio yang masuk ditranskripsikan terlebih dahulu agar diproses oleh Sales Brain dalam alur yang sama dengan chat teks.", tone: "bg-violet-50 text-violet-700" },
  { number: "03", icon: Bot, title: "Sales Brain mengambil keputusan aman", detail: "Gemini memahami intent, emosi, dan menyusun bahasa. LightGBM dan guardrail Python menentukan harga serta melindungi floor price.", tone: "bg-fuchsia-50 text-fuchsia-700" },
  { number: "04", icon: CreditCard, title: "Checkout memberi bukti transaksi", detail: "Midtrans mengirim status pembayaran. Supabase menyimpan order, payment event, reservasi, dan mutasi stok secara teraudit.", tone: "bg-emerald-50 text-emerald-700" },
];

const checklist = [
  "Kirim satu chat teks: tanya produk lalu lakukan negosiasi wajar.",
  "Kirim satu voice note singkat: pastikan transkrip dan balasan masuk ke percakapan yang sama.",
  "Buka Live Demo: tunjukkan intent, emosi, harga final, floor price, dan alasan guardrail.",
  "Selesaikan satu checkout Sandbox: verifikasi order paid, payment success, reservasi confirmed, dan stok berkurang.",
];

export default function SettingsPage() {
  return <div className="space-y-8 pb-10">
    <header className="overflow-hidden rounded-[2rem] bg-gradient-to-br from-indigo-950 via-[#33216d] to-[#715bc9] p-7 text-white shadow-2xl shadow-indigo-300/30 md:p-9">
      <div className="flex flex-wrap items-start justify-between gap-5"><div className="max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-1 text-xs font-bold uppercase tracking-[0.16em] text-indigo-100"><Sparkles className="h-3.5 w-3.5" /> Sistem & bukti demo</div><h1 className="mt-4 text-3xl font-black tracking-tight md:text-4xl">LARISKA bekerja sebagai Sales Brain, bukan chatbot biasa.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-indigo-100">Halaman ini adalah peta operasional yang jujur untuk demo: siapa pelanggan, bagaimana voice note diproses, siapa yang memutuskan harga, dan bagaimana pembayaran tercatat.</p></div><div className="rounded-2xl border border-emerald-300/30 bg-emerald-400/10 px-4 py-3 text-sm font-bold text-emerald-100"><span className="mr-2 inline-block h-2 w-2 rounded-full bg-emerald-300" />Guardrail harga terkunci</div></div>
    </header>

    <section><div className="mb-4"><p className="text-sm font-bold uppercase tracking-[0.16em] text-[#715bc9]">Alur pelanggan nyata</p><h2 className="mt-1 text-2xl font-black text-indigo-950">Dari WhatsApp sampai stok terbarui</h2></div><div className="grid gap-4 lg:grid-cols-4">{stages.map((stage) => { const Icon = stage.icon; return <article key={stage.number} className="relative rounded-3xl border border-white bg-white/85 p-5 shadow-lg shadow-indigo-100/35"><span className="absolute right-5 top-4 text-xs font-black text-slate-300">{stage.number}</span><div className={`mb-5 inline-flex rounded-2xl p-3 ${stage.tone}`}><Icon className="h-6 w-6" /></div><h3 className="pr-7 text-lg font-black leading-tight text-indigo-950">{stage.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{stage.detail}</p></article>; })}</div></section>

    <section className="grid gap-5 xl:grid-cols-[1.2fr_0.8fr]"><article className="rounded-3xl border border-indigo-100 bg-white/90 p-6 shadow-xl shadow-indigo-100/35"><div className="flex items-start gap-3"><div className="rounded-2xl bg-indigo-50 p-3 text-[#715bc9]"><ShieldCheck className="h-6 w-6" /></div><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-[#715bc9]">Keputusan yang dapat dijelaskan</p><h2 className="mt-1 text-2xl font-black text-indigo-950">Batas peran AI dibuat tegas</h2></div></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><Evidence title="Gemini" body="Memahami pesan, emosi, dan menulis respons Indonesia yang ramah serta kontekstual." /><Evidence title="LightGBM + Python" body="Menghasilkan keputusan harga dari sinyal yang tersedia dan menjalankan guardrail bisnis." /><Evidence title="Floor price" body="Tidak dapat dilanggar oleh prompt, respons Gemini, atau perubahan tampilan dashboard." /></div><div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm leading-6 text-amber-900"><strong>Catatan demo:</strong> harga final yang muncul di Live Demo adalah hasil keputusan upstream. Gemini tidak diberi kewenangan untuk menurunkan harga sendiri.</div></article>
      <article className="rounded-3xl border border-emerald-100 bg-gradient-to-br from-white to-emerald-50 p-6 shadow-xl shadow-emerald-100/35"><div className="flex items-center gap-3"><div className="rounded-2xl bg-emerald-100 p-3 text-emerald-700"><Database className="h-6 w-6" /></div><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-emerald-700">Sumber kebenaran</p><h2 className="mt-1 text-xl font-black text-indigo-950">Data tidak hidup di UI</h2></div></div><p className="mt-5 text-sm leading-6 text-slate-600">Katalog, stok, floor price, pelanggan, percakapan, order, dan status pembayaran dibaca dari backend/Supabase. Dashboard ini tidak menyediakan tombol edit palsu untuk komponen kritis.</p><div className="mt-5 rounded-2xl bg-emerald-900 p-4 text-sm text-emerald-50"><p className="font-bold">Untuk video Proof of Work</p><p className="mt-1 leading-6 text-emerald-100">Tunjukkan dashboard setelah tindakan nyata di WhatsApp dan checkout; jangan jadikan dashboard sebagai pengganti alur inti pelanggan.</p></div></article></section>

    <section className="rounded-3xl border border-white bg-white/85 p-6 shadow-xl shadow-indigo-100/35"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-[#715bc9]">Checklist pagi demo</p><h2 className="mt-1 text-2xl font-black text-indigo-950">Empat bukti yang paling kuat untuk ditampilkan</h2></div><span className="rounded-full bg-indigo-50 px-3 py-1.5 text-xs font-bold text-[#715bc9]">Fokus MVP · bukan menu berlebih</span></div><ol className="mt-6 grid gap-3 md:grid-cols-2">{checklist.map((item, index) => <li key={item} className="flex gap-3 rounded-2xl border border-slate-100 bg-slate-50/80 p-4"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-[#715bc9] text-xs font-black text-white">{index + 1}</span><p className="text-sm font-medium leading-6 text-slate-700">{item}</p></li>)}</ol><div className="mt-5 flex items-center gap-2 text-sm font-semibold text-emerald-700"><CheckCircle2 className="h-5 w-5" />Satu alur end-to-end yang terbukti lebih kuat daripada banyak fitur yang hanya statis.</div></section>
  </div>;
}

function Evidence({ title, body }: { title: string; body: string }) { return <div className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><p className="font-black text-indigo-950">{title}</p><p className="mt-2 text-sm leading-6 text-slate-600">{body}</p></div>; }
